default:
  tags:
    - docker

image: ubuntu:jammy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - deploy

deploy-job:
  stage: deploy
  environment: production
  script:
    - '[[ ! -z "$CI_KEY" ]] || (echo "Warning: \$CI_KEY not set" && exit 1)'
    - apt-get update
    - apt-get install --no-install-recommends --assume-yes gnupg git devscripts
    - cat $CI_KEY | gpg --batch --import
    - echo $CI_PASS | gpg --batch --always-trust --yes --passphrase-fd 0 --pinentry-mode=loopback -s $(mktemp)
    - gpg --fingerprint
    - ls -la
    - git status
    - git config --global user.email "code@hxr.io"
    - git config --global user.name "HXR CI"
    - git merge --allow-unrelated-histories origin/main
    - ls -la
    - debuild -i -S
